blog_project/blog_app/urls.py
from django.urls import path
from .views import *
app_name = 'blog_app'
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('signup/', SignupView.as_view(), name="signup"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', logout_view, name="logout"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('myblogs/', MyBlogsView.as_view(), name="myblogs"),
    path('create_blog/', BlogCreateView.as_view(), name="create_blog"),
    path("update_blog/<int:pk>/", BlogUpdateView.as_view(), name="update_blog"),
    path("delete_blog/<int:pk>/", BlogDeleteView.as_view(), name="blog_delete"),
    path("update_bio/", update_bio, name="update_bio"),
    path("update_profile_picture/", update_profile_picture, name="update_profile_picture"),
    path("blog/<int:pk>/", Blog_Detail_View.as_view(), name="blog_detail"),
    path("blog_like/<int:id>/", like_view, name="blog_like"),
    path("create_comment_view/<int:blog_id>/", create_comment_view, name="create_comment_view"),
    path("delete_comment/<int:comment_id>/", delete_comment, name="delete_comment"),
    path("comment_edit/<int:comment_id>/", edit_comment, name="edit_comment")
]

blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls', namespace="blog_app")),
    
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    

blog_project/blog_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    phone = models.CharField(max_length=15, null=True, blank=True)
    profile_picture = models.ImageField(upload_to="profiles", null=True, blank=True)
    profession = models.CharField(max_length=100)
    bio = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.username

class Blog(models.Model):
    title = models.CharField( max_length=50)
    body = models.TextField()
    feature_image = models.ImageField(upload_to='feature_images')
    blogger = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField( auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    blogger = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=250)


class Like(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    blogger = models.ForeignKey(User, on_delete=models.CASCADE)
    


    

blog_project/blog_app/forms.py
from django import forms
from .models import User, Blog, Comment, Like

class SignupForm(forms.ModelForm):
    confirm_password = forms.CharField(max_length=128, widget = forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ['first_name', 'last_name', "username", 'email', 'phone', 'profession', 'password']

        widgets = {
            'first_name': forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs= { 'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={ 'class': 'form-control'}),
            'phone': forms.TextInput(attrs ={'class': 'form-control'}),
            'profession': forms.TextInput(attrs={'class':'form-control'}),
            'password': forms.PasswordInput(attrs= { 'class': 'form-control'})
        }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError("Passwords does not match!")
        


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=128,widget=forms.PasswordInput(attrs={'class':'form-control'}))


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'body', 'feature_image']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'body': forms.Textarea(attrs= { 'class': 'form-control', 'id':"editor1"}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content':forms.TextInput(attrs={'class':'form-control'})
        }
    


     

blog_project/blog_app/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, FormView, View, UpdateView, DeleteView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.forms import ValidationError
from .models import *
from .forms import SignupForm, LoginForm, BlogForm, CommentForm
# Create your views here.


class HomeView(TemplateView):
    template_name = "./blog_app/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_blogs'] = Blog.objects.all().order_by("-id")[:4]
        return context
    


class SignupView(CreateView):
    form_class = SignupForm
    model = User
    success_url = reverse_lazy('blog_app:home')
    template_name = "./blog_app/signup.html"

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()
        return redirect(self.success_url)

class LoginView(FormView):
    form_class = LoginForm
    success_url = reverse_lazy('blog_app:home')
    template_name = "./blog_app/login.html"

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(self.request, user)
        else:
            print("User not found")
            return redirect(reverse('blog_app:login') + '?error=Credientials not matched!')
        if next := self.request.GET.get('next'):
            return redirect(next)
        return redirect(self.success_url)

@login_required
def logout_view(request):
    logout(request)
    return redirect('blog_app:home')


class ProfileView(LoginRequiredMixin,TemplateView):
    login_url = '/login/'
    template_name = 'blog_app/blogger/blogger_admin.html'


class MyBlogsView(LoginRequiredMixin, TemplateView):
    login_url = '/login/'
    template_name = 'blog_app/blogger/myblogs.html'


class BlogCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    template_name = 'blog_app/blogger/create_blog.html'
    form_class = BlogForm
    success_url = reverse_lazy('blog_app:myblogs')

    def form_valid(self, form):
        form.instance.blogger = self.request.user
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'

    template_name = 'blog_app/blogger/update_blog.html'
    form_class = BlogForm
    model = Blog
    success_url = reverse_lazy('blog_app:myblogs')



class BlogDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Blog
    success_url = reverse_lazy('blog_app:myblogs')


@login_required
def update_bio(request):
    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        user.bio = request.POST.get('bio')
        user.save()
    return redirect('blog_app:profile')


@login_required
def update_profile_picture(request):
    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        user.profile_picture = request.FILES.get('profile_picture')
        print(request.FILES.get('profile_picture'))
        user.save()
    return redirect('blog_app:profile')


class Blog_Detail_View(DetailView):
    template_name = 'blog_app/blog.html'
    model = Blog

    def dispatch(self, request, *args, **kwargs):
        if request.method.lower() in self.http_method_names:
            handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
        else:
            handler = self.http_method_not_allowed

        blog = get_object_or_404(Blog,id=int(kwargs.get('pk')))
        blog.views = blog.views + 1
        blog.save()
        return handler(request, *args, **kwargs)

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['likes'] = Like.objects.filter(blog=int(self.kwargs.get('pk'))).count()
        if Like.objects.filter(blog=int(self.kwargs.get('pk')), blogger=self.request.user.id).count() != 0:
            context['color'] = "red"
        else:
            context['color'] = "black"
        context['comments'] = Comment.objects.filter(blog=int(self.kwargs.get('pk')))
        return context
    




@login_required(login_url="/login/")
def like_view(request,id):
    if Like.objects.filter(blog=int(id), blogger=request.user.id).count() == 0:
        like = Like(blog=get_object_or_404(Blog,id=int(id)), blogger=request.user)
        like.save()
    else:
        like = Like.objects.get(blog=get_object_or_404(Blog,id=int(id)), blogger=request.user)
        like.delete()
    return redirect('blog_app:blog_detail', pk=int(id))


def create_comment_view(request, blog_id):
    if request.method == "POST":
        content = request.POST.get('comment')
        blogger = request.user
        blog = Blog.objects.get(id=int(blog_id))

        comment = Comment(content=content, blogger=blogger, blog=blog)
        comment.save()
    return redirect('blog_app:blog_detail', pk=int(blog_id))


@login_required(login_url="/login/")
def delete_comment(request, comment_id):
    comment = Comment.objects.get(id = int(comment_id))
    blog_id = comment.blog.id
    comment.delete()
    return redirect('blog_app:blog_detail', pk=int(blog_id))


@login_required(login_url="/login/")
def edit_comment(request, comment_id):
    if request.method == "POST":
        comment = Comment.objects.get(id=int(comment_id))
        comment.content = request.POST.get('comment')
        blog_id = comment.blog.id
        comment.save()
    return redirect('blog_app:blog_detail', pk=blog_id)

blog_project/templates/blog_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dev Speak</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    {% include 'blog_app/navbar.html' %}
    {% block content %}
        
    {% endblock content %}
    {% include 'blog_app/footer.html' %}
    
</body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"></script>

</html>

blog_project/templates/blog_app/blog.html
{% extends 'blog_app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
    <div class="container">
        <h2>{{blog.title}}</h2>
        <img src="{{blog.feature_image.url}}" style="width:100%; margin-bottom: 30px;">
        {{blog.body | safe}}
        <p><span style="font-weight: bold;">Writer: </span><span>{{blog.blogger}}</span></p>
        <p><span style="font-weight: bold;">Created_at:</span> <span>{{blog.created_at}}</span></p>
        <p><span style="font-weight: bold;"> Updated_at: </span><span>{{blog.updated_at}}</span></p>
        <p>
            <a href="{%url 'blog_app:blog_like' blog.id %}" style="color:{{color}}"><i class="fa fa-thumbs-up"></i> : {{likes}} 
            {% if color == "black" %}
                Like
            {% else %}
                Unlike
            {% endif %}
                </a>
            <spann style="margin-left:40%"><i class="fa fa-eye"></i> : {{blog.views}}</spann>
            <span id="comment" style="float: right; cursor: pointer">Comment</span></p>
            
            {% if request.user.is_authenticated %}
            <form method="POST" id="form" style="display: none" action="{% url 'blog_app:create_comment_view' blog.id %}" >
                {% csrf_token %}
                <input type="text" name="comment" />
                <button>Submit</button>
            </form>
            {% else %}
            <p>Please login to comment</p>
            {% endif %}

            
            {% for comment in comments %}
               <p>
                   {{comment.blogger}} : {{comment.content}} 
                    {% if request.user.id  == comment.blogger.id %} 
                    <span id="edit" style="cursor:pointer">Edit</span> 
                    <a href="{% url 'blog_app:delete_comment' comment.id%}">Delete</a>
                    <form method="POST" id="edit_form" style="display: none" action="{% url 'blog_app:edit_comment' comment.id %}" >
                        {% csrf_token %}
                        <input type="text" name="comment" />
                        <button>Submit</button>
                    </form>
                    {% endif %} 
                </p> 
            {% endfor %}
                
                
            
    </div>
    <script>
        var hide = true;
        var x = document.getElementById('comment')
        var y = document.getElementById('form')
        x.addEventListener(
            'click', function(){
                console.log("clicked")
                hide = !hide;
                if(hide){
                    y.style.display = 'none'
                }
                else{
                    y.style.display = 'block'
                }
            }
        )

        var hide_edit = true;
        var xx = document.getElementById('edit')
        var yx = document.getElementById('edit_form')
        xx.addEventListener(
            'click', function(){
                console.log("clicked")
                hide_edit = !hide_edit;
                if(hide_edit){
                    yx.style.display = 'none'
                }
                else{
                    yx.style.display = 'block'
                }
            }
        )



    </script>
    
{% endblock content %}
    

blog_project/templates/blog_app/footer.html
<footer class="container-fluid">
    <div class="wrapper">
      <div class="row">
        <div class="col-md-4 first">
          <h3>DEV SPEAK</h3>
          <form>
            <input type="email" placeholder="Enter email to receive updates and newsletter"/>
          </form>
          <p>Connect with us</p>
          <ul>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-youtube"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
          </ul>
        </div>
        <div class="col-md-4 second">
          <h3>Quick Links</h3>
          <ul>
            <li><a>About us</a></li>
            <li><a>contact us</a></li>
            <li><a>Home</a></li>
            <li><a>Blogs</a></li>
          </ul>
        </div>
        <div class="col-md-4 third">
          <h3>Contact us</h3>
          <p><span>Email: </span>devspeak@gmail.com</p>
          <p><span>Contact:</span>+077 0868122399</span></p>
          <p><span>Address:</span>Patan Durbar Square, Lalitpur</span></p>
        </div>
      </div>
    </div>
</footer>

blog_project/templates/blog_app/index.html
{% extends 'blog_app/base.html' %}
{% load static %}
{% block content %}
    
<div class="home">
    <div class="container-fluid mt-1 hero">
        <div class="row bg-hero">
         <div class="col-md-6">
             <h2>Hello Devs, <br>Hold coffee and write some inspiring </h2>
         </div>
         <div class="col-md-6">
             <img src="{% static 'hero.webp' %}" title="">
         </div>
        </div>
    </div>
    <div class="container intro">
         <div class="row">
             <div class="col-md-6">
                 <img src="{% static 'inspire.png' %}">
             </div>
             <div class="col-md-6">
                 <h2>
                     Dev Speak Allows You To Write Your Views and Wake Other Devs
                 </h2>
             </div>
         </div>
     </div>
    <div class="container-fluid latest">
        <h2>Latest Posts</h2>
        <div class="row">
                {% for blog in latest_blogs  %}
                <div class="col-md-3">
                    <a href="{% url 'blog_app:blog_detail' blog.id %}">
                        <img src="{{blog.feature_image.url}}" alt=""> 
                        <h3>{{blog.title}}</h3>
                    </a>
                </div>
                {% endfor %}
        </div>
     </div>
     <div class="container-fluid popular">
        <h2>Popular Among Devs</h2>
        <div class='row'>
            <div class="col-md-3">
                <img src="{% static 'blog1.jpg' %}" alt="">
                <h3>Lets code and have a fun!</h3>
            </div>
            <div class="col-md-3">
                <img src="{% static 'blog2.jpg' %}" alt="">
                <h3>Lets code and have a fun!</h3>
            </div>
            <div class="col-md-3">
                <img src="{% static 'blog3.jpg' %}" alt="">
                <h3>Lets code and have a fun!</h3>
            </div>
            <div class="col-md-3">
                <img src="{% static 'blog4.jpg' %}" alt="">
                <h3>Lets code and have a fun!</h3>
            </div>
        </div>
     </div>
     <div class="container-fluid liked">
        <h2>Most Liked Posts</h2>
        <div class='row'>
            <div class="col-md-3">
                <img src="{% static 'blog1.jpg' %}" alt="">
                <h3>Lets code and have a fun!</h3>
            </div>
            <div class="col-md-3">
                <img src="{% static 'blog2.jpg' %}" alt="">
                <h3>Lets code and have a fun!</h3>
            </div>
            <div class="col-md-3">
                <img src="{% static 'blog3.jpg' %}" alt="">
                <h3>Lets code and have a fun!</h3>
            </div>
            <div class="col-md-3">
                <img src="{% static 'blog4.jpg' %}" alt="">
                <h3>Lets code and have a fun!</h3>
            </div>
        </div>
     </div>
     
</div>
{% endblock content %}
    

blog_project/templates/blog_app/login.html
{% extends 'blog_app/base.html' %}

{% block content %}
    <form method="POST" class="col-md-5 mx-auto my-4">
        {% csrf_token %}
        
        {% if request.GET.error %}
            <p class="text-danger">{{request.GET.error}}</p>
        {% endif %}
            
        {{form}}
        <button class="btn btn-danger my-3">Login</button>
        
    </form>
{% endblock content %}
    

blog_project/templates/blog_app/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom shadow-sm">
    <a class="navbar-brand pr-2" href="#">
      <img src="{% static 'logo.PNG'%}" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Blogs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact us</a>
        </li>
        
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <p class="nav-link">Welcome {{request.user}}</p>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog_app:profile' %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog_app:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog_app:signup' %}">SignUp</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'blog_app:login'%}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

blog_project/templates/blog_app/signup.html
{% extends 'blog_app/base.html' %}


{% block content %}
    <div class="card col-md-6 mx-auto my-4">
        <h3>Sign up Form</h3>
        <form method="post"> 
            {% csrf_token %}
            {{form}}
            <button type="submit" class="btn btn-success mt-3">Signup</button>
        </form>
    </div>
{% endblock content %}
    