blog_project/blog_app/urls.py
from django.urls import path
from .views import *
app_name = 'blog_app'
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('signup/', SignupView.as_view(), name="signup"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', logout_view, name="logout"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('myblogs/', MyBlogsView.as_view(), name="myblogs"),
    path('create_blog/', BlogCreateView.as_view(), name="create_blog"),
    path("update_blog/<int:pk>/", BlogUpdateView.as_view(), name="update_blog"),
    path("delete_blog/<int:pk>/", BlogDeleteView.as_view(), name="blog_delete"),
    path("update_bio/", update_bio, name="update_bio"),
    path("update_profile_picture/", update_profile_picture, name="update_profile_picture"),
    path("blog/<int:pk>/", Blog_Detail_View.as_view(), name="blog_detail"),
    path("blog_like/<int:id>/", like_view, name="blog_like"),
    path("create_comment_view/<int:blog_id>/", create_comment_view, name="create_comment_view"),
    path("delete_comment/<int:comment_id>/", delete_comment, name="delete_comment"),
    path("comment_edit/<int:comment_id>/", edit_comment, name="edit_comment")
]

blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls', namespace="blog_app")),
    
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    

blog_project/blog_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    phone = models.CharField(max_length=15, null=True, blank=True)
    profile_picture = models.ImageField(upload_to="profiles", null=True, blank=True)
    profession = models.CharField(max_length=100)
    bio = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.username

class Blog(models.Model):
    title = models.CharField( max_length=50)
    body = models.TextField()
    feature_image = models.ImageField(upload_to='feature_images')
    blogger = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField( auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    blogger = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=250)


class Like(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    blogger = models.ForeignKey(User, on_delete=models.CASCADE)
    


    

blog_project/blog_app/forms.py
from django import forms
from .models import User, Blog, Comment, Like

class SignupForm(forms.ModelForm):
    confirm_password = forms.CharField(max_length=128, widget = forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ['first_name', 'last_name', "username", 'email', 'phone', 'profession', 'password']

        widgets = {
            'first_name': forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs= { 'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={ 'class': 'form-control'}),
            'phone': forms.TextInput(attrs ={'class': 'form-control'}),
            'profession': forms.TextInput(attrs={'class':'form-control'}),
            'password': forms.PasswordInput(attrs= { 'class': 'form-control'})
        }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError("Passwords does not match!")
        


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=128,widget=forms.PasswordInput(attrs={'class':'form-control'}))


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'body', 'feature_image']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'body': forms.Textarea(attrs= { 'class': 'form-control', 'id':"editor1"}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content':forms.TextInput(attrs={'class':'form-control'})
        }
    


     

blog_project/blog_app/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, FormView, View, UpdateView, DeleteView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.forms import ValidationError
from .models import *
from .forms import SignupForm, LoginForm, BlogForm, CommentForm
# Create your views here.


class HomeView(TemplateView):
    template_name = "./blog_app/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_blogs'] = Blog.objects.all().order_by("-id")[:4]
        return context
    


class SignupView(CreateView):
    form_class = SignupForm
    model = User
    success_url = reverse_lazy('blog_app:home')
    template_name = "./blog_app/signup.html"

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()
        return redirect(self.success_url)

class LoginView(FormView):
    form_class = LoginForm
    success_url = reverse_lazy('blog_app:home')
    template_name = "./blog_app/login.html"

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(self.request, user)
        else:
            print("User not found")
            return redirect(reverse('blog_app:login') + '?error=Credientials not matched!')
        if next := self.request.GET.get('next'):
            return redirect(next)
        return redirect(self.success_url)

@login_required
def logout_view(request):
    logout(request)
    return redirect('blog_app:home')


class ProfileView(LoginRequiredMixin,TemplateView):
    login_url = '/login/'
    template_name = 'blog_app/blogger/blogger_admin.html'


class MyBlogsView(LoginRequiredMixin, TemplateView):
    login_url = '/login/'
    template_name = 'blog_app/blogger/myblogs.html'


class BlogCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    template_name = 'blog_app/blogger/create_blog.html'
    form_class = BlogForm
    success_url = reverse_lazy('blog_app:myblogs')

    def form_valid(self, form):
        form.instance.blogger = self.request.user
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'

    template_name = 'blog_app/blogger/update_blog.html'
    form_class = BlogForm
    model = Blog
    success_url = reverse_lazy('blog_app:myblogs')



class BlogDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Blog
    success_url = reverse_lazy('blog_app:myblogs')


@login_required
def update_bio(request):
    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        user.bio = request.POST.get('bio')
        user.save()
    return redirect('blog_app:profile')


@login_required
def update_profile_picture(request):
    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        user.profile_picture = request.FILES.get('profile_picture')
        print(request.FILES.get('profile_picture'))
        user.save()
    return redirect('blog_app:profile')


class Blog_Detail_View(DetailView):
    template_name = 'blog_app/blog.html'
    model = Blog

    def dispatch(self, request, *args, **kwargs):
        if request.method.lower() in self.http_method_names:
            handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
        else:
            handler = self.http_method_not_allowed

        blog = get_object_or_404(Blog,id=int(kwargs.get('pk')))
        blog.views = blog.views + 1
        blog.save()
        return handler(request, *args, **kwargs)

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['likes'] = Like.objects.filter(blog=int(self.kwargs.get('pk'))).count()
        if Like.objects.filter(blog=int(self.kwargs.get('pk')), blogger=self.request.user.id).count() != 0:
            context['color'] = "red"
        else:
            context['color'] = "black"
        context['comments'] = Comment.objects.filter(blog=int(self.kwargs.get('pk')))
        return context
    




@login_required(login_url="/login/")
def like_view(request,id):
    if Like.objects.filter(blog=int(id), blogger=request.user.id).count() == 0:
        like = Like(blog=get_object_or_404(Blog,id=int(id)), blogger=request.user)
        like.save()
    else:
        like = Like.objects.get(blog=get_object_or_404(Blog,id=int(id)), blogger=request.user)
        like.delete()
    return redirect('blog_app:blog_detail', pk=int(id))


def create_comment_view(request, blog_id):
    if request.method == "POST":
        content = request.POST.get('comment')
        blogger = request.user
        blog = Blog.objects.get(id=int(blog_id))

        comment = Comment(content=content, blogger=blogger, blog=blog)
        comment.save()
    return redirect('blog_app:blog_detail', pk=int(blog_id))


@login_required(login_url="/login/")
def delete_comment(request, comment_id):
    comment = Comment.objects.get(id = int(comment_id))
    blog_id = comment.blog.id
    comment.delete()
    return redirect('blog_app:blog_detail', pk=int(blog_id))


@login_required(login_url="/login/")
def edit_comment(request, comment_id):
    if request.method == "POST":
        comment = Comment.objects.get(id=int(comment_id))
        comment.content = request.POST.get('comment')
        blog_id = comment.blog.id
        comment.save()
    return redirect('blog_app:blog_detail', pk=blog_id)

blog_project/templates/blog_app/blogger/blogger_admin.html
{% extends 'blog_app/base.html' %}
{% load static %}

{% block content %}
    
    <div style="width:95%; margin:auto; padding: auto">
        <div class="row">
            <div class="col-md-3 bg-secondary">
                <ul style="list-style-type: none;">
                    <li><a  style="color: white;" href="{% url 'blog_app:profile'%}">Profile</a></li>
                    <li><a  style="color: white;" href="{% url 'blog_app:myblogs'%}">MyBlogs</a></li>
                </ul>
                
            </div>
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-6">
                        <h4 class="mt-4">{{request.user}} </h4>
                    </div>
                    <div class="col-md-6">
                            <img 
                            {% if request.user.profile_picture %}
                            src="{{request.user.profile_picture.url}}" 
                            {% else %}
                            src="{% static 'profile.jpg'%}"
                            {% endif %}
                            style="height:150px; width:150px; border-radius: 50%;"> 
                            <p data-toggle="modal" data-target="#change_profile" style="cursor: pointer;">Upload new</p>
                            <div class="modal fade" id="change_profile" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title" id="exampleModalLabel">Update profile picture</h5>
                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                      </button>
                                    </div>
                                    <div class="modal-body">
                                      <form method="POST" action="{% url 'blog_app:update_profile_picture' %}" enctype="multipart/form-data">
                                          {% csrf_token %}
                                          <input type="file" accept="image/*" name="profile_picture">
                                          <button type="submit" class="btn btn-warning">Save changes</button>
                                      </form>
                                    </div>
                                  </div>
                                </div>
                              </div>
                        
                    </div>
                </div>
            
                
                <h1>Personal Info</h1>
                <table class="table table-bordered table-striped">
                    <tr>
                        <td><h5>Name</h5></td>
                        <td><h5>{{request.user.first_name}} {{request.user.last_name}}</h5></td>
                
                    </tr>
                    <tr>
                        <td><h5>Email</h5></td>
                        <td><h5>{{request.user.email}}</h5></td>
                    </tr>
                    <tr>
                        <td><h5>Phone</h5></td>
                        <td><h5>{{request.user.phone}}</h5></td>
                    </tr>
                    <tr>
                        <td><h5>Profession</h5></td>
                        <td><h5>{{request.user.profession}}</h5></td>
                    </tr>
                    <tr>
                        <td><h5>Bio</h5></td>
                        <td><h5>{{request.user.bio}}</h5></td>
                        <td><span data-toggle="modal" data-target="#update_bio_modal" style="cursor:pointer; color:blueviolet">Add/Edit Bio</span></td>
                        <div class="modal fade" id="update_bio_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h5 class="modal-title" id="exampleModalLabel">Add/Update Bio</h5>
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                                <div class="modal-body">
                                  <form method="POST" action="{% url 'blog_app:update_bio' %}">
                                      {% csrf_token %}
                                      <textarea class="form-control mb-2" name="bio">{{request.user.bio}}</textarea>
                                      <button type="submit" class="btn btn-warning">Save changes</button>
                                  </form>
                                </div>
                              </div>
                            </div>
                          </div>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
    

blog_project/templates/blog_app/blogger/create_blog.html
{% extends 'blog_app/base.html' %}
{% load static %}

{% block content %}
    <script src="{% static 'ckeditor/ckeditor.js'%}"></script>
    <div style="width:95%; margin:auto; padding: auto">
        <div class="row my-4">
            <div class="col-md-3 bg-secondary">
                <ul style="list-style-type: none;">
                    <li><a  style="color: white;"href="{% url 'blog_app:profile'%}">Profile</a></li>
                    <li><a style="color: white;" href="{% url 'blog_app:myblogs'%}">MyBlogs</a></li>
                </ul>
                
            </div>
            <div class="col-md-9">
                <h2>Create and publish new blog</h2>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form}}
                    <br>
                    <button type="submit" class="btn btn-success">Publish</button>
                </form>
            </div>
        </div>
    </div>
    <script>
        CKEDITOR.replace('editor1');
    </script>
{% endblock content %}
    

blog_project/templates/blog_app/blogger/myblogs.html
{% extends 'blog_app/base.html' %}


{% block content %}
    
    <div style="width:95%; margin:auto; padding: auto">
        <div class="row my-4">
            <div class="col-md-3 bg-secondary">
                <ul style="list-style-type: none;">
                    <li><a  style="color: white;"href="{% url 'blog_app:profile'%}">Profile</a></li>
                    <li><a style="color: white;" href="{% url 'blog_app:myblogs'%}">MyBlogs</a></li>
                </ul>
                
            </div>
            <div class="col-md-9">
                <h1>MyBlogs<a href="{% url 'blog_app:create_blog' %}"><span style="float:right; font-size: 16px;" class="btn btn-danger">+Write New</span></a></h1>
                <table class="table table-bordred table-striped">
                    
                    {% for blog in request.user.blog_set.all %}
                        <tr>
                            <th>{{blog.title}}</th>
                            <th>
                                <form method="POST" action="{% url 'blog_app:blog_delete' blog.id%}">
                                    {% csrf_token %}
                                    <button type="submit"  class="btn btn-danger" onclick="delete_blog(event)">Delete</button>
                                </form>
                            </th>
                            <th><a href="{% url 'blog_app:update_blog' blog.id%}">Update</a></th>
                        </tr>
                    {% endfor %}
                        
                </table>
            </div>
        </div>
    </div>
    <script>
        const delete_blog = e =>{
            e.preventDefault();
            const x = confirm("Are you sure?")
            if(x){
                e.target.form.submit();
            }
        }
    </script>
{% endblock content %}
    

blog_project/templates/blog_app/blogger/update_blog.html
{% extends 'blog_app/base.html' %}
{% load static %}


{% block content %}
<script src="{% static 'ckeditor/ckeditor.js'%}"></script>
<div style="width:95%; margin:auto; padding: auto">
    <div class="row my-4">
        <div class="col-md-3 bg-secondary">
            <ul style="list-style-type: none;">
                <li><a  style="color: white;"href="{% url 'blog_app:profile'%}">Profile</a></li>
                <li><a style="color: white;" href="{% url 'blog_app:myblogs'%}">MyBlogs</a></li>
            </ul>
            
        </div>
        <div class="col-md-9">
            <h1>Update a blog</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form}}
                <br>
                <button type="submit" class="btn btn-success">Re publish</button>
            </form>
        </div>
    </div>
</div>
<script>
    CKEDITOR.replace('editor1');
</script>
{% endblock content %}
    